# Building a neural network


In [4]:
import tensorflow as tf
from tensorflow.keras import layers, Sequential
import numpy as np

In [6]:
x = np.array([[350.0, 45]])

layer1 = layers.Dense(units=3, activation='sigmoid')
a1 = layer1(x)
print(a1)

layer2 = layers.Dense(units=1, activation='sigmoid')
a2 = layer2(a1)
print(a2)

tf.Tensor([[0. 0. 1.]], shape=(1, 3), dtype=float32)
tf.Tensor([[0.5301645]], shape=(1, 1), dtype=float32)


In [9]:
#create a data set

X = np.array([[400.0, 30.0],
              [475.0, 35.0],
              [470.0, 36.0],
              [500.0, 30.0],
              [250.0, 25.0],
              [330.0, 38.0],
              [350.0, 50.0],
              [350.0, 40.0],
              [350.0, 45.0],            
              ])

y = np.array([1, 1, 1, 0, 0, 1, 0, 1, 1])

In [7]:
# sequential function

# layer1 = layers.Dense(units=3, activation='sigmoid')
# layer2 = layers.Dense(units=1, activation='sigmoid')
# model = Sequential([layer1, layer2])

model = Sequential([layers.Dense(units=3, activation='sigmoid'),
                    layers.Dense(units=1, activation='sigmoid')])

#model.compile()
#model.fit()
#model.predict(x_new)


In [8]:
from tensorflow.keras.losses import BinaryCrossentropy

model.compile(loss=BinaryCrossentropy())


In [10]:
model.fit(X, y, epochs=100) # Epochs => number of steps in gradient descent

Epoch 1/100
1/1 [==============================] - 0s 459ms/step - loss: 0.8039
Epoch 2/100
1/1 [==============================] - 0s 5ms/step - loss: 0.8003
Epoch 3/100
1/1 [==============================] - 0s 6ms/step - loss: 0.7977
Epoch 4/100
1/1 [==============================] - 0s 5ms/step - loss: 0.7956
Epoch 5/100
1/1 [==============================] - 0s 5ms/step - loss: 0.7937
Epoch 6/100
1/1 [==============================] - 0s 12ms/step - loss: 0.7920
Epoch 7/100
1/1 [==============================] - 0s 6ms/step - loss: 0.7904
Epoch 8/100
1/1 [==============================] - 0s 6ms/step - loss: 0.7889
Epoch 9/100
1/1 [==============================] - 0s 5ms/step - loss: 0.7875
Epoch 10/100
1/1 [==============================] - 0s 6ms/step - loss: 0.7861
Epoch 11/100
1/1 [==============================] - 0s 6ms/step - loss: 0.7848
Epoch 12/100
1/1 [==============================] - 0s 6ms/step - loss: 0.7835
Epoch 13/100
1/1 [==============================] - 0s 5ms

In [11]:
x_new = [[300.0, 30.0]]
model.predict(x_new)

1/1 [==============================] - 0s 97ms/step


array([[0.4837912]], dtype=float32)