# Binary classification


In [10]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Dataset

In [11]:
path = "./datasets/"
dataset = pd.read_csv(path+'Iris.csv')
dataset = dataset[:100]

data = dataset.sample(frac=1).reset_index(drop=True)
print(data[:5])

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0  36            5.0           3.2            1.2           0.2   
1  87            6.7           3.1            4.7           1.5   
2  50            5.0           3.3            1.4           0.2   
3  95            5.6           2.7            4.2           1.3   
4  35            4.9           3.1            1.5           0.1   

           Species  
0      Iris-setosa  
1  Iris-versicolor  
2      Iris-setosa  
3  Iris-versicolor  
4      Iris-setosa  


In [13]:
data["Species"] = data["Species"].apply(lambda x: x.replace("Iris-setosa", "0"))
data["Species"] = data["Species"].apply(lambda x: x.replace("Iris-versicolor", "1"))
data = data.astype(float)
print(data[:10])

     Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0  36.0            5.0           3.2            1.2           0.2      0.0
1  87.0            6.7           3.1            4.7           1.5      1.0
2  50.0            5.0           3.3            1.4           0.2      0.0
3  95.0            5.6           2.7            4.2           1.3      1.0
4  35.0            4.9           3.1            1.5           0.1      0.0
5  78.0            6.7           3.0            5.0           1.7      1.0
6  75.0            6.4           2.9            4.3           1.3      1.0
7  82.0            5.5           2.4            3.7           1.0      1.0
8  24.0            5.1           3.3            1.7           0.5      0.0
9  40.0            5.1           3.4            1.5           0.2      0.0


In [14]:
X = data.iloc[:, 1:5].values
y = data.iloc[:, 5:6].values
y = y.astype(int)
print(X[:5])
print(y[:5])

print(np.shape(X))  
print(np.shape(y))

[[5.  3.2 1.2 0.2]
 [6.7 3.1 4.7 1.5]
 [5.  3.3 1.4 0.2]
 [5.6 2.7 4.2 1.3]
 [4.9 3.1 1.5 0.1]]
[[0]
 [1]
 [0]
 [1]
 [0]]
(100, 4)
(100, 1)


In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=10)

print(len(data))
print(len(X_train))
print(len(X_test))


100
80
20


# Tensor Flow Model

In [19]:
model = Sequential(
    [
        Dense(4, activation="relu", name="layer1"),
        Dense(1, activation="sigmoid", name="layer2")
    ]
)

In [20]:
model.compile(
    loss= tf.keras.losses.BinaryCrossentropy(),
    optimizer= tf.keras.optimizers.Adam(0.01),
)

In [21]:
model.fit(X_train, y_train, epochs=100)

Epoch 1/100
3/3 [==============================] - 1s 5ms/step - loss: 1.2393
Epoch 2/100
3/3 [==============================] - 0s 3ms/step - loss: 1.0704
Epoch 3/100
3/3 [==============================] - 0s 3ms/step - loss: 0.9662
Epoch 4/100
3/3 [==============================] - 0s 4ms/step - loss: 0.8940
Epoch 5/100
3/3 [==============================] - 0s 3ms/step - loss: 0.8158
Epoch 6/100
3/3 [==============================] - 0s 5ms/step - loss: 0.7409
Epoch 7/100
3/3 [==============================] - 0s 3ms/step - loss: 0.6790
Epoch 8/100
3/3 [==============================] - 0s 3ms/step - loss: 0.6216
Epoch 9/100
3/3 [==============================] - 0s 19ms/step - loss: 0.5673
Epoch 10/100
3/3 [==============================] - 0s 3ms/step - loss: 0.5160
Epoch 11/100
3/3 [==============================] - 0s 3ms/step - loss: 0.4698
Epoch 12/100
3/3 [==============================] - 0s 5ms/step - loss: 0.4266
Epoch 13/100
3/3 [==============================] - 0s 2ms/s

In [22]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer1 (Dense)              (None, 4)                 20        
                                                                 
 layer2 (Dense)              (None, 1)                 5         
                                                                 
Total params: 25 (100.00 Byte)
Trainable params: 25 (100.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [23]:
L1_num_params = 4*4 + 4
L2_num_params = 4*1 + 1
print("L1 num params: ", L1_num_params, " L2 num params: ", L2_num_params)

L1 num params:  20  L2 num params:  5


# Performance Analysis

In [25]:
predictions = model.predict(X_test)
accuracy = tf.keras.metrics.CategoricalAccuracy()(y_test, predictions).numpy()
print(f'Accuracy: {accuracy*100:.2f}%')

1/1 [==============================] - 0s 20ms/step
Accuracy: 100.00%


In [26]:
binaryPred = (predictions > 0.5).astype(int)

for i in range(len(y_test)):
    print(f'Actual: %d - Pred: %d'%(y_test[i], binaryPred[i]))
    

Actual: 0 - Pred: 0
Actual: 0 - Pred: 0
Actual: 0 - Pred: 0
Actual: 1 - Pred: 1
Actual: 1 - Pred: 1
Actual: 1 - Pred: 1
Actual: 0 - Pred: 0
Actual: 1 - Pred: 1
Actual: 1 - Pred: 1
Actual: 1 - Pred: 1
Actual: 0 - Pred: 0
Actual: 1 - Pred: 1
Actual: 0 - Pred: 0
Actual: 1 - Pred: 1
Actual: 0 - Pred: 0
Actual: 1 - Pred: 1
Actual: 1 - Pred: 1
Actual: 1 - Pred: 1
Actual: 1 - Pred: 1
Actual: 1 - Pred: 1


C:\Users\Kaleb\AppData\Local\Temp\ipykernel_3352\574348693.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print(f'Actual: %d - Pred: %d'%(y_test[i], binaryPred[i]))


In [28]:
print("Generate a prediction for a single sample")
sample1 = np.array([5.1, 2.5, 3.0, 1.1])
sample2 = np.array([4.4, 3.0, 1.3, .2])

sample = sample2.reshape((1, len(sample2)))
predSample = model.predict(sample)

print(f"Prediction: {predSample}")
print(f"Predictions: {(predSample>0.5).astype(int)}")

Generate a prediction for a single sample
1/1 [==============================] - 0s 22ms/step
Prediction: [[0.00507289]]
Predictions: [[0]]


In [29]:
W1, b1 = model.get_layer("layer1").get_weights()
W2, b2 = model.get_layer("layer2").get_weights()
print("W1:\n", W1, "\nb1:\n", b1)
print("W2:\n", W2, "\nb2:\n", b2)

W1:
 [[ 0.5896717   0.4016144   0.47352844  0.75838816]
 [ 0.7856165  -0.84743446  0.15543866  0.24039821]
 [-0.63642335  0.63494784  0.09724827 -0.28013858]
 [-0.2762492   1.8590498   1.4797034  -0.9822325 ]] 
b1:
 [ 0.4978974  -0.37050658 -0.3764768   0.4444901 ]
W2:
 [[-0.9852292]
 [ 1.5832086]
 [ 0.5895937]
 [-0.5005398]] 
b2:
 [-0.4184152]
